name: Minor Fix
description: Describe a minor issue related to a major feature (e.g., behavior definition for corner cases, refactor)
body:
  - type: textarea
    attributes:
      label: Subject
      placeholder: >
        The related major feature is ...
  - type: textarea
    attributes:
      label: Expected Behavior
      placeholder: >
        What I expect for the feature is that when ... The motivation is that ...
  - type: textarea
    attributes:
      label: Actual Behavior
      placeholder: >
        The current implementation ...
